theme: jekyll-theme-slate
title: [Traffic Camera Pipeline]
description: [Xinhe Ren*, David Wang*, Michael Laskey, Ken Goldberg]
show_downloads: [true]
github:
  zip_url: https://drive.google.com/file/d/1ny3AbVo3tkXoHReigeDO1dYhHpg9rxXS/view?usp=sharing
