theme: jekyll-theme-slate
title: [Traffic Camera Pipeline]
description: [Learning Driving Behavior at Traffic Intersections via Automated Extraction of Trajectories from Online Video Streams]
show_downloads: [true]
github:
  zip_url: https://drive.google.com/file/d/1ny3AbVo3tkXoHReigeDO1dYhHpg9rxXS/view?usp=sharing
